### ISSUE TITLE
Use `base` version constraint as a proxy for compatible GHC versions

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/setup-agda#105]
We currently use the contents of the `tested-with` field and the presence of `stack-X.Y.Z.yaml` files to derive compatible GHC versions. @andreasabel has pointed out that the `base` package version constraints are a more _robust_ and _uniform_ indication of compatible GHC versions:

- _Robust_ because it's better maintained by the Agda developers.
- _Uniform_ because it works for both Cabal and Stack.

Unfortunately, there are several downsides:

- It would likely require us to store a mapping of base versions to GHC versions, unless there's a future-proof formula to convert between them.
- It would increase the maintenance burden, as the mapping of base versions to GHC versions would need to be maintained.
- It would require us to be able to reliably extract the `base` version constraints from `Agda.cabal` without parsing the file, as there is no JavaScript port of `Cabal-syntax`.

I like the idea, but I'll need to do further research to see how much effort it would be to implement and maintain.

**Comment by andreasabel** [comment]
> * mapping of base versions to GHC versions, unless there's a future-proof formula to convert between them.

For GHC x.y with 7 <= x <= 9 you need base 4.z with z = 3 + 6(x-7) + y/2.  However this formula relies on the coincidence that .10 was the last minor version for both GHC 7 and 8.
:-D

Re: `tested-with`:
Hackage allows updating the `tested-with`, but also if some dependencies are revised _at the same time_.  If one tries to just update `tested-with`, Hackage will tell one that one "should not bother to make this revision".

Re: `stack-x.y.z.yaml`:
These files cannot be added as part of a Hackage revision, so we would need to release a patch version to update these.  We have not done so in the past and it seems to be an overkill.  

I added a mapping from Agda version to GHC versions here: https://wiki.portal.chalmers.se/agda/Main/Download (I just realize that I didn't update this according to the latest revisions).
Maybe we can maintain this mapping in a machine-readable version somewhere else, and generate a human-friendly version somewhere.

**Comment by wenkokke** [comment]
Closing this in favour of #148, since the `base` constraints aren't accurate enough. For instance, 2.6.2.1 doesn't compile with GHC 9.2.4 due to the version of `bytestring` that ships with that version of GHC, even if its `base` constraint matches.
