### ISSUE TITLE
Find additional server space for prebuilt Agda binaries

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/setup-agda#120]
@andreasabel Would Chalmers or GU be able to offer us some server space to host the prebuilt Agda binaries? They're not terribly large, around 30MB per build.

**Comment by wenkokke** [comment]
I've also asked the CIS at Strathclyde for hosting.

**Comment by wenkokke** [comment]
@andreasabel Would it be possible to attach the binaries to the GitHub releases for each Agda version?

**Comment by andreasabel** [comment]
> @andreasabel Would it be possible to attach the binaries to the GitHub releases for each Agda version?

@wenkokke This would be the easiest solution. 
There seem no limits to what you can attach to a release as long as each file is below 2GB.

**Comment by wenkokke** [comment]
> > @andreasabel Would it be possible to attach the binaries to the GitHub releases for each Agda version?
> 
> @wenkokke This would be the easiest solution. There seem no limits to what you can attach to a release as long as each file is below 2GB.

The downside  is that it'd still be hosted by GitHub, so vulnerable to the same 404's that I'm seeing occasionally now.

**Comment by andreasabel** [comment]
> The downside is that it'd still be hosted by GitHub, so vulnerable to the same 404's that I'm seeing occasionally now.

Did you find any documentation/issues on this?

**Comment by andreasabel** [comment]
@wenkokke:  Good you could resolve this issue.  How was it resolved?

**Comment by wenkokke** [comment]
There's additional hosting provided by the MSP group.

**Comment by wenkokke** [comment]
Thanks for reminding me to document the reason :)

**Comment by andreasabel** [comment]
> There's additional hosting provided by the MSP group.

Must be: https://msp.cis.strath.ac.uk/
