### ISSUE TITLE
Gather licenses for Haskell dependencies

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/setup-agda#122]
This should probably be done by inspecting the Cabal build plan *during the build* and collecting the license from each package, much like NPM does.

1. Run `cabal configure` to generate `plan.json`;
2. For each dependency in `plan.json`: add the package name, version, and license to a big `licenses.txt` file.

There's some option questions:

- Is `cabal configure` enough or do we need to run `cabal build --only-dependencies`?
- Do we need to run `cabal get` to get the source, or can we easily find out where it is kept on the local system from `plan.json`?
- Does `plan.json` transitively include all dependencies? I'm assuming it _must_, but I don't know for sure.
- Does each sdist have a `LICENSE` file? I don't think so. I'm afraid we need to inspect the `.cabal` file to get the `license-file` field—and use that file path—or the `license` field—and automatically generate a license text from the correct template.

@L-TChen Could you lend your expertise here? Do you know the answers to any of my questions? Did you have a different strategy in mind?

**Comment by L-TChen** [comment]
The Agda dev team discussed this issue [here](https://github.com/agda/agda/issues/5202) sometime ago, and here is my [attempt](https://github.com/haskell/cabal/pull/7443) which I didn’t finish. cabal is seemingly complex to me, and I was distracted by something else.

`plan.json` does not seem to include this information (`extra-libraries`) in [`Cabal.Plan`](https://hackage.haskell.org/package/cabal-plan-0.7.2.3/docs/Cabal-Plan.html), so for example icu4c (which has a different license from `text-icu`) is not mentioned.

**Comment by wenkokke** [comment]
@L-TChen I assumed it would be sufficient to package a `licenses.txt` in the binary package, rather than having to embed the file. Is there a reason it should be embedded? If we package them together, then anyone who separates them and redistributes them individually is breaking the license agreement, not us.

**Comment by wenkokke** [comment]
@L-TChen Thank you! The hint to use `cabal-plan` was incredibly useful. I didn't know Agda already had the infrastructure to generate a (partial) license report.

**Comment by L-TChen** [comment]
Yes, if you intend to solve the problem for Agda only, then it might just be fine to include a license report using `cabal-plan` with some copyright notices included manually and check its completeness whenever Agda adds a new dependency.

**Comment by wenkokke** [comment]
Actually, linked libraries are obviously not gonna cut it, 'cuz we're not distributing those.

What we'd need to know is what libraries GHC automatically bundles into the executable...?
Shouldn't those be covered by some GHC license somewhere, e.g., for builds using gmp?

**Comment by wenkokke** [comment]
Fixed in #130 and #134. We now have the option to include a `licenses.txt` file with Cabal builds.
