### ISSUE TITLE
Anything blocking a release supporting Agda 2.6.4.1 ?

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#205]
PR #200 added Agda 2.6.4.1, but it is not included in `latest` yet: https://github.com/andreasabel/logrel-mltt/actions/runs/7638686155/job/20810107980?pr=1

Anything blocking 2.6.4.1 ?

**Comment by wenkokke** [comment]
I would venture a guess that this was blocked in a large part on me not knowing 2.6.4.1 was released.

**Comment by wenkokke** [comment]
Oh, nope, I knew, did part of the work, then forgot.

**Comment by wenkokke** [comment]
Retagged latest. Should work now.
