### ISSUE TITLE
Error: Unknown Agda version '2.6.4', but it could be because 'std-lib-version: 2.0'

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#206]
https://github.com/graded-type-theory/graded-type-theory/actions/runs/7639460249/job/20812498678?pr=22#step:3:28
> Error: Unknown Agda version '2.6.4'

I suspect this is not the actual error, but it could be caused because the requested std-lib version `2.0` is not listed as compatible with `2.6.4` in this file:
https://github.com/wenkokke/setup-agda/blob/d25d411bf0ff0cda5d9c3b3e6abd2d391fda451f/data/Agda.versions.yml#L43-L44
https://github.com/wenkokke/setup-agda/blob/d25d411bf0ff0cda5d9c3b3e6abd2d391fda451f/data/Agda.versions.yml#L80-L81

**Comment by wenkokke** [comment]
Happy to accept a PR.

**Comment by andreasabel** [comment]
I think our PRs crossed, so I closed mine.

Besides updating the `.yml` files in `data/`, do I have to run a script?  Your PR also includes changes to some auto-generated file...

**Comment by wenkokke** [comment]
You always need to run the pre-commit hooks, or manually run `./hooks/pre-commit`.

**Comment by andreasabel** [comment]
Are these running automatically on `git commit` or I need to configure something for this to happen?

**Comment by wenkokke** [comment]
![Screenshot 2024-01-25 at 12 10 00](https://github.com/wenkokke/setup-agda/assets/3983973/a8a1694d-d7a2-46d0-ab80-7dc355e7e527)

**Comment by andreasabel** [comment]
Ah sorry for not reading the manual properly...

Thanks for adding std-lib 2.0!

**Comment by wenkokke** [comment]
> Ah sorry for not reading the manual properly...

Ah, sorry, I did not mean to imply that. You made a good point for this information to be duplicated in the section for the standard library.
