### ISSUE TITLE
Problem with version of `base`

### ISSUE THREAD

**Issue by tomaz1502** [wenkokke/setup-agda#217]
TLDR: Is there anyway to set a different version for `base`, instead of `4.20.0.0`?

I want to set an action for a project that depends on `agda2hs`. Adding `agda2hs` in `agda-libraries` does not work, since this only adds this package as a library, and I need the binary to generate some files. I am trying to run `cabal install agda2hs` before compiling my project, but it does not work since `agda2hs` requires `base` >= 4.10 and < 4.20 and the version of `base` in this image is `4.20.0.0` independent of which version of `agda` I choose.

**Comment by wenkokke** [comment]
If you're already running cabal install to get agda2hs, then presumably you don't need Agda? What are you hoping to use this action for?

**Comment by wenkokke** [comment]
For reference, this action isn't an image, and doesn't set any version of base.

**Comment by wenkokke** [comment]
You can influence the version of base that is installed _in case an install of GHC is necessary_ by setting the GHC version, but note that that isn't guaranteed to actually install GHC, and it'd make more sense for you to use the setup Haskell action directly.

**Comment by tomaz1502** [comment]
If I try to install agda2hs on top of Haskell's action, for instance, it takes 20 minutes to build Agda first (and also some errors are thrown, which I could not understand yet). My hope was to use this action to speed up this process with this action.

**Comment by wenkokke** [comment]
This action downloads and sets up Agda binaries, but does not install the Agda library or any of its dependencies in any way that GHC would recognise and be able use and link against.

Short answer: No, this action cannot help you. Try running cabal install and caching the relevant directories with [actions/cache](https://github.com/actions/cache).
