### ISSUE TITLE
Tag `latest` points to `v2.3` not `v2.4` (the actual latest).

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#222]
Tag `latest` points to `v2.3` not `v2.4` (the actual latest).  Likely it was forgotten to update it.
See: https://github.com/wenkokke/setup-agda/pull/218#issuecomment-2421637240

**Comment by wenkokke** [comment]
Closing, since latest now points to HEAD (and should always point to HEAD).
