### ISSUE TITLE
Publish to GitHub Actions marketplace

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/setup-agda#31]
Should be discussed with @omelkonian, as it requires either renaming this action—which would be confusing—or deprecating [`omelkonian/setup-agda`] in favour of this action—which probably requires this action to *at least* be able to setup the standard library.

[`omelkonian/setup-agda`]: https://github.com/omelkonian/setup-agda

**Comment by wenkokke** [comment]
Pinging @omelkonian!

**Comment by wenkokke** [comment]
Thanks!

**Comment by wenkokke** [comment]
Guess I have to wait for Marketplace to realise the action was delisted?

**Comment by omelkonian** [comment]
At least this returns 404 now: https://github.com/marketplace/actions/setup-agda

**Comment by wenkokke** [comment]
It seems that I cannot publish this action because my account was limited with no notification, presumably because of the CI usage of this action.

**Comment by wenkokke** [comment]
Fixed upstream, and published!
